name: Build

on:
  # push:
  #   branches: [ sidekick ]
  pull_request:
    branches: [ sidekick ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run test:lint